### ISSUE TITLE
Installation/Configuration

### ISSUE THREAD

**Issue by alcy** [httpdss/collectd-web#29]
1.) Setting collectd's datadir in collection.conf to collectd-web's directory ( eg., /var/www/collectd-web), doesn't work. Collectd still writes its data to the default directory (/var/lib/collectd/rrd).
Not an issue fpr collectd-web, but I thought you should be notified. So to make collectd write to a different directory, one should edit the RRDTool Plugin in collectd.conf to reflect a different directory. Experienced this with collectd 4.9.1 on Debian. 

2) After that's taken care of, and collectd is succesfully writing its data under collectd-web/<hostname>, collectd-web interface doesn't show much except a Hosts field. No plugins or hosts to pick from. And I am really lost there. I have tried both the stable tarball and code from github. 

3) Just to make sure that my apache config was ok, I tried using the standalone python server, with the same behavior. You can see the messages:

Collectd-web server running at http://127.0.0.1:8888/
localhost - - [06/Sep/2010 12:45:52] "GET / HTTP/1.1" 200 -
localhost - - [06/Sep/2010 12:45:52] "GET /media/css/blueprint/screen.css HTTP/1.1" 200 -
localhost - - [06/Sep/2010 12:45:52] "GET /media/css/blueprint/print.css HTTP/1.1" 200 -
localhost - - [06/Sep/2010 12:45:52] "GET /media/css/custom-theme/jquery-ui-1.8.custom.css HTTP/1.1" 200 -
localhost - - [06/Sep/2010 12:45:52] "GET /media/css/base.css HTTP/1.1" 200 -
localhost - - [06/Sep/2010 12:45:52] "GET /media/js/jquery-1.4.2.min.js HTTP/1.1" 200 -
localhost - - [06/Sep/2010 12:45:52] "GET /media/js/jquery.livequery.js HTTP/1.1" 200 -
localhost - - [06/Sep/2010 12:45:52] "GET /media/js/jquery-ui-1.8.custom.min.js HTTP/1.1" 200 -
localhost - - [06/Sep/2010 12:45:52] "GET /media/js/jquery.jclock.js HTTP/1.1" 200 -
localhost - - [06/Sep/2010 12:45:52] "GET /media/js/external/TimeSpan-1.2.min.js HTTP/1.1" 200 -
localhost - - [06/Sep/2010 12:45:52] "GET /media/js/jquery.validate.pack.js HTTP/1.1" 200 -
localhost - - [06/Sep/2010 12:45:52] "GET /media/js/base.js HTTP/1.1" 200 -
localhost - - [06/Sep/2010 12:45:52] "GET /media/js/graph-menu.js HTTP/1.1" 200 -
localhost - - [06/Sep/2010 12:45:52] "GET /media/images/loading.gif HTTP/1.1" 200 -
localhost - - [06/Sep/2010 12:45:52] "GET /media/css/custom-theme/images/ui-bg_gloss-wave_35_f6a828_500x100.png HTTP/1.1" 200 -
localhost - - [06/Sep/2010 12:45:52] "GET /media/css/custom-theme/images/ui-bg_highlight-soft_100_eeeeee_1x100.png HTTP/1.1" 200 -
localhost - - [06/Sep/2010 12:45:53] "GET /cgi-bin/collection.modified.cgi?action=hostlist_json HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/lib/python2.6/CGIHTTPServer.py", line 255, in run_cgi
    os.execve(scriptfile, args, os.environ)
OSError: [Errno 13] Permission denied
localhost - - [06/Sep/2010 12:45:53] CGI script exit status 0x7f00
localhost - - [06/Sep/2010 12:45:53] "GET /cgi-bin/time.cgi HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/lib/python2.6/CGIHTTPServer.py", line 255, in run_cgi
    os.execve(scriptfile, args, os.environ)
OSError: [Errno 13] Permission denied
localhost - - [06/Sep/2010 12:45:53] CGI script exit status 0x7f00
localhost - - [06/Sep/2010 12:45:55] "GET /media/images/shortcut-icon.png HTTP/1.1" 200 -

**Comment by farfabet** [comment]
Hi,

Just to confirm and complete what slazarp is saying. 
You have to make sure that collectd-web path is accessible to user nobody, basically I had the issue because I was lauching the standalone from /root/collectd-web which is not accessible to anyone but root.

I moved it in /opt/ for a cleaner setup and it worked fine.
